"""Internal markdown anchors on the Confluence backend are reported, not resolved.

See src/docspan/backends/confluence/anchors.py for why reporting is the whole
scope: Confluence anchors are page-scoped and generated by its own rules, and no
instance was available to establish the format against. A guessed href would be
the same dead link the Google Docs backend was fixed for.
"""
from __future__ import annotations

import pytest

from docspan.backends.confluence.anchors import (
    internal_anchors_in_markdown,
    render_dead_anchors,
)


class TestFindingInternalAnchors:
    @pytest.mark.parametrize(
        "content, expected",
        [
            ("see [A1](#a1-current-state)\n", ["#a1-current-state"]),
            # Distinct, in first-use order, deduped.
            ("[a](#one) [b](#two) [c](#one)\n", ["#one", "#two"]),
            # A real URL is not an anchor.
            ("[x](https://example.com)\n", []),
            # A bare fragment in prose is not a link destination.
            ("the #hashtag is not a link\n", []),
            ("", []),
        ],
    )
    def test_only_fragment_destinations_are_found(
        self, content: str, expected: list[str]
    ) -> None:
        assert internal_anchors_in_markdown(content) == expected

    def test_a_fragment_inside_a_code_fence_is_not_a_link(self) -> None:
        # Anchored on "](#", so prose and code that merely contains a `#` is safe.
        assert internal_anchors_in_markdown("```\n#a1-current-state\n```\n") == []


class TestRendering:
    def test_the_warning_names_the_anchors_and_says_what_to_do(self) -> None:
        message = render_dead_anchors(["#one", "#two"])
        assert "#one" in message and "#two" in message
        # The point is that a reader lands nowhere — the author needs to know the
        # link does not work, not merely that something was unusual.
        assert "lands" in message and "plain text" in message

    def test_more_than_five_are_truncated(self) -> None:
        message = render_dead_anchors([f"#a{n}" for n in range(8)])
        assert "… and 3 more" in message
