"""Internal markdown anchors on the Confluence backend are reported, not resolved.

See src/docspan/backends/confluence/anchors.py for why reporting is the whole
scope: Confluence anchors are page-scoped and generated by its own rules, and no
instance was available to establish the format against. A guessed href would be
the same dead link the Google Docs backend was fixed for.
"""
from __future__ import annotations

import pytest

from docspan.backends.confluence.anchors import (
    internal_anchors_in_markdown,
    render_dead_anchors,
)


class TestFindingInternalAnchors:
    @pytest.mark.parametrize(
        "content, expected",
        [
            ("see [A1](#a1-current-state)\n", ["#a1-current-state"]),
            # Distinct, in first-use order, deduped.
            ("[a](#one) [b](#two) [c](#one)\n", ["#one", "#two"]),
            # A real URL is not an anchor.
            ("[x](https://example.com)\n", []),
            # A bare fragment in prose is not a link destination.
            ("the #hashtag is not a link\n", []),
            ("", []),
        ],
    )
    def test_only_fragment_destinations_are_found(
        self, content: str, expected: list[str]
    ) -> None:
        assert internal_anchors_in_markdown(content) == expected

    def test_a_fragment_inside_a_code_fence_is_not_a_link(self) -> None:
        # Anchored on "](#", so prose and code that merely contains a `#` is safe.
        assert internal_anchors_in_markdown("```\n#a1-current-state\n```\n") == []


class TestRendering:
    def test_the_warning_names_the_anchors_and_says_what_to_do(self) -> None:
        message = render_dead_anchors(["#one", "#two"])
        assert "#one" in message and "#two" in message
        # The point is that a reader lands nowhere — the author needs to know the
        # link does not work, not merely that something was unusual.
        assert "lands" in message and "plain text" in message

    def test_more_than_five_are_truncated(self) -> None:
        message = render_dead_anchors([f"#a{n}" for n in range(8)])
        assert "… and 3 more" in message


class TestCodeIsNotProse:
    """A link inside code is documentation, not a link.

    The regex is not block-aware, so a page documenting anchor syntax inside a
    ```` ```markdown ```` fence had its own example reported — a warning, and a
    non-zero exit, for a page containing no link at all.
    """

    @pytest.mark.parametrize(
        "content",
        [
            "```markdown\nsee [A1](#a1-current-state)\n```\n",
            "~~~\n[A1](#x)\n~~~\n",
            "write `[A1](#a1)` like so\n",
            "````\n[a](#deep-fence)\n````\n",
        ],
    )
    def test_a_link_in_code_is_not_reported(self, content: str) -> None:
        assert internal_anchors_in_markdown(content) == []

    def test_a_real_link_after_a_fence_is_still_found(self) -> None:
        content = "```\n[a](#in-fence)\n```\n\nsee [b](#real)\n"
        assert internal_anchors_in_markdown(content) == ["#real"]

    def test_a_titled_link_inside_a_fence_is_not_reported(self) -> None:
        content = '```markdown\nsee [A1](#a1 "Some Title")\n```\n'
        assert internal_anchors_in_markdown(content) == []

    def test_a_four_backtick_fence_containing_three_backtick_text_is_bounded_correctly(
        self,
    ) -> None:
        content = "````\nhere is ``` inline-looking text and [a](#in-fence)\n````\n\nsee [b](#real)\n"
        assert internal_anchors_in_markdown(content) == ["#real"]


class TestMatchingTheParsersOwnPattern:
    def test_a_link_with_a_title_is_reported(self) -> None:
        """`InlineParser.PATTERNS["link"]` accepts a title; this must too.

        Omitting it made a genuinely dead `#fragment` href reach Confluence
        unreported — a false negative in the one job this module has.
        """
        assert internal_anchors_in_markdown('[A1](#a1-titled "Some Title")\n') == [
            "#a1-titled"
        ]

    def test_an_image_is_not_reported_as_a_link(self) -> None:
        """`![alt](#f)` becomes a media node, so "a reader clicking one lands
        nowhere" would be the wrong thing to say about it."""
        assert internal_anchors_in_markdown("![alt](#f)\n") == []
