"""Internal markdown anchors (`[A1](#a1-current-state)`) as Google Docs heading links.

A Google Doc has no URL fragment, so a link whose href is `#a1-current-state`
is stored verbatim and is a **dead link** for every reader of the Doc. The Docs
API's `Link` is a union of six members — `url`, `tabId`, `bookmark`, `heading`,
and the legacy `bookmarkId`/`headingId` — and every heading paragraph already
carries a `headingId` in its `paragraphStyle`, so the target exists; the anchor
just has to be resolved to it. Which of `heading` / `headingId` a *read* returns
depends on `includeTabsContent`, not on the document; see
`DocsStructureParser._parse_link`.

Both directions go through this module for the document body, so they cannot
drift there. They do **not** cover table cells: `_parse_table` flattens a cell
to a plain string, so a heading inside a cell is not an anchor target and a
heading link inside a cell is dropped on read — pre-existing for `url` links
too, and out of scope here, but the invariant above is about paragraphs only.

* write — markdown `#target` -> ``{"headingId": ...}`` (`link_payload`)
* read  — ``{"headingId": ...}`` -> markdown `#slug` (`heading_id_to_slug`)

`#target` is resolved against the document by **exact heading id first, then
slug** (`resolve_anchor`). Matching ids by set membership rather than by a
`h.xxxx` shape guess means the read direction can emit a bare id when a slug is
unavailable and the write direction will still resolve it, with no invented
escape syntax and no assumption about how Docs formats an id.

A leading `#` is the only discriminator needed between an anchor and a URL — no
absolute or relative URL begins with one — so `TextSpan.link` keeps carrying a
single string rather than growing a parallel "is this an anchor" field.

Out of scope, deliberately: bookmarks (`bookmarkId`), cross-document anchors,
and the Confluence backend.
"""
from __future__ import annotations

import unicodedata
from typing import Dict, Iterable, List, Optional, Sequence, Tuple
from urllib.parse import unquote

# Characters github-slugger keeps besides the categories below. Space is kept
# here and turned into "-" afterwards, which is what makes the double-hyphen
# case work.
_KEPT = frozenset("-_ ")

# Unicode general categories github-slugger keeps: letters, decimal and letter
# numbers, combining marks, and connector punctuation. It is generated as a
# character class of everything to *remove*, so this is its complement stated as
# categories — see slugify() for what that costs and why it is not the blob.
#
# `Mn`/`Mc`/`Me` are the load-bearing entries. `str.isalnum()` is False for a
# combining mark, so slugging "café" in NFD (an `e` followed by U+0301, which is
# how macOS often hands text over) dropped the accent and produced
# "cafe-measurements" where GitHub produces "café-measurements" — an anchor that
# silently resolves to nothing. `No` is the other direction: "x²" kept the ²
# where GitHub drops it.
_KEPT_CATEGORIES = frozenset(
    {"Ll", "Lu", "Lt", "Lm", "Lo", "Nd", "Nl", "Mn", "Mc", "Me", "Pc"}
)



def slugify(text: str) -> str:
    """Slug a single heading as GitHub does, ignoring duplicates.

    Mirrors `github-slugger` (the implementation GitHub's markdown pipeline
    uses, https://github.com/Flet/github-slugger): lowercase, drop punctuation
    and symbols, then replace each remaining space with a hyphen.

    Two details that a naive `re.sub(r"\\s+", "-", ...)` gets wrong, and that a
    cross-reference silently fails to match on:

    * Spaces are replaced **one at a time**, never as a run. `## A1 — Current`
      loses the em dash and keeps both spaces that surrounded it, so the slug is
      `a1--current` with *two* hyphens.
    * A tab is *dropped*, not turned into a hyphen — only U+0020 is.

    Fidelity, measured rather than asserted:
    `tests/fixtures/github_slugger_vectors.json` holds outputs generated by
    running the real github-slugger, and `tests/test_heading_anchors.py` checks
    this function against every one of them. Two documented divergences, both
    recorded in that fixture:

    * Leading/trailing whitespace. github-slugger alone turns `"  Intro  "`
      into `"--intro--"`; the `.strip()` here yields `"intro"`, which is parity
      with **GitHub end to end**, because a markdown parser trims ATX heading
      text before the slugger ever sees it.
    * Circled letters, and roughly 150 other exotic code points across the BMP.
      This keeps whole Unicode *categories* (`_KEPT_CATEGORIES`) where
      github-slugger ships an 8 KB generated character class. The exact count is
      deliberately not stated: it moves with both the slugger's version and
      Python's Unicode tables, and two independent measurements of it disagreed
      by a handful. What is stable is the shape — 52 circled letters
      (U+24B6–U+24E9) that the slugger keeps and this drops, plus letters from
      scripts added to Unicode after that class was generated, which this keeps
      and the slugger drops. Embedding the blob would trade those for a frozen
      Unicode version, so the categories win; the residue is exotic enough
      (Glagolitic, Old Polish, medievalist Latin) that no real heading is
      expected to hit it, and one that does gets a reported unresolvable anchor
      rather than a silently wrong link.
    """
    lowered = text.strip().lower()
    kept = "".join(
        char
        for char in lowered
        if unicodedata.category(char) in _KEPT_CATEGORIES or char in _KEPT
    )
    return kept.replace(" ", "-")


def slugify_all(texts: Iterable[str]) -> List[str]:
    """Slug headings in document order, applying GitHub's duplicate suffixes.

    The second heading slugging to `intro` becomes `intro-1`, the third
    `intro-2`. The suffix search loops until it finds an unused slug rather
    than trusting the counter, because a document can contain a *literal*
    heading "Intro 1" whose own slug is already `intro-1` — github-slugger
    handles that by skipping to `intro-2`, and a bare counter would hand two
    different headings the same anchor.

    Order matters, so this takes the whole sequence: a slug's suffix is a fact
    about the headings before it, not about the heading itself.
    """
    occurrences: Dict[str, int] = {}
    slugs: List[str] = []
    for text in texts:
        base = slugify(text)
        slug = base
        while slug in occurrences:
            occurrences[base] = occurrences.get(base, 0) + 1
            slug = f"{base}-{occurrences[base]}"
        occurrences[slug] = 0
        slugs.append(slug)
    return slugs


def is_heading_style(style: object) -> bool:
    """Whether a paragraph's namedStyleType is an anchor target.

    `TITLE` and `SUBTITLE` count. Google Docs' own outline treats them as
    document-level headings and `projection.project()` maps them to
    `HEADING_1`/`HEADING_2` because that is what markdown can express — so an
    anchor to a document's title has a real target and a
    `startswith("HEADING_")` test silently refuses it.

    This matters on the **read** side. Markdown `#` parses to `HEADING_1`, *not*
    to `TITLE` — so the push path never consults a TITLE style, and a test there
    cannot detect this branch. What produces a TITLE paragraph is Google Docs
    itself, for every document whose title was typed into the title bar.
    Confirmed against a live Doc that such a paragraph does carry a `headingId`.
    """
    return isinstance(style, str) and (
        style.startswith("HEADING_") or style in ("TITLE", "SUBTITLE")
    )


def _heading_texts_and_ids(nodes: Iterable[object]) -> List[Tuple[str, Optional[str]]]:
    """(text, heading_id) for every heading paragraph, in document order.

    Headings with no `headingId` are still returned. They cannot be linked to,
    but they must occupy their slot so the duplicate suffixes of the headings
    after them stay aligned with what GitHub would produce for the same
    markdown.
    """
    out: List[Tuple[str, Optional[str]]] = []
    for node in nodes:
        if not is_heading_style(getattr(node, "style", "")):
            continue
        out.append((getattr(node, "text", "") or "", getattr(node, "heading_id", None)))
    return out


def heading_slug_to_id(nodes: Iterable[object]) -> Dict[str, str]:
    """slug -> headingId for every linkable heading, in document order."""
    pairs = _heading_texts_and_ids(nodes)
    slugs = slugify_all(text for text, _ in pairs)
    return {
        slug: heading_id
        for slug, (_, heading_id) in zip(slugs, pairs)
        if heading_id
    }


def heading_id_to_slug(nodes: Iterable[object]) -> Dict[str, str]:
    """headingId -> slug, the inverse map the read direction needs."""
    return {heading_id: slug for slug, heading_id in heading_slug_to_id(nodes).items()}


def heading_slugs(nodes: Iterable[object]) -> List[str]:
    """Every heading's slug in document order, linkable or not.

    Used by unresolved_anchors(), where the markdown-side heading nodes have no
    ids yet and only their slugs matter.
    """
    return slugify_all(text for text, _ in _heading_texts_and_ids(nodes))


def _match_keyed(slug_to_id: Dict[str, str]) -> Dict[str, str]:
    """``slug_to_id`` re-keyed for comparison against an ``anchor_target``.

    Only the *keys* are normalized. The values, and the slugs
    ``heading_id_to_slug`` writes into pulled markdown, stay exactly as
    ``slugify`` produced them, so github-slugger parity is unaffected.
    """
    return {unicodedata.normalize("NFC", slug): heading_id for slug, heading_id in slug_to_id.items()}


def is_anchor(href: Optional[str]) -> bool:
    """True for an internal anchor. No URL, absolute or relative, starts with `#`.

    A bare "#" is not an anchor — it names no heading and is a link to the top
    of the page in a browser, which has no Docs equivalent.
    """
    if href is None:
        return False
    return href.startswith("#") and len(href) > 1


def anchor_target(href: str) -> str:
    """The part of an anchor after the `#`, as a key comparable with a slug.

    Two transformations, both required for a non-ASCII anchor to resolve at all:

    * **Percent-decode.** A CommonMark parser normalizes link destinations by
      percent-encoding them, so `[Café](#café-notes)` reaches this module as
      `#caf%C3%A9-notes` — measured, not assumed::

          >>> mistune.create_markdown(renderer=None)('[Café](#café-notes)')
          ... {'type': 'link', 'attrs': {'url': '#caf%C3%A9-notes'}}

      The slug side is built from the heading's own text and is never encoded,
      so without decoding here the two can never meet and every accented anchor
      silently resolves to nothing. GitHub decodes for the same reason.
    * **NFC-normalize.** The decoded href and the heading text can carry the
      same characters in different normalization forms — macOS hands text over
      in NFD, most editors write NFC — and `slugify` deliberately keeps
      combining marks, so `café` in NFD and in NFC produce slugs that look
      identical and compare unequal. Normalizing here rather than inside
      `slugify` keeps the emitted slug byte-comparable with github-slugger,
      which does not normalize; this is a divergence in the comparison key
      only, never in the slug a pull writes into the markdown.
    """
    return unicodedata.normalize("NFC", unquote(href[1:]))


def resolve_anchor(
    href: str,
    slug_to_id: Dict[str, str],
    known_ids: Optional[Iterable[str]] = None,
) -> Optional[str]:
    """Resolve an anchor to a headingId, or None when it names no heading.

    Heading id first, then slug. The id branch is what closes the round trip:
    a pull that could not name a slug for some heading emits the bare id, and
    this resolves it back without either side inventing a syntax for "this is
    an id, not a slug".

    Both sides are compared on ``anchor_target``'s key, so a slug built from
    NFD heading text still matches an href the markdown parser handed over in
    NFC — see ``anchor_target``.
    """
    target = anchor_target(href)
    ids = known_ids if isinstance(known_ids, (set, frozenset, dict)) else set(known_ids or ())
    if target in ids:
        return target
    return _match_keyed(slug_to_id).get(target)


def link_payload(
    href: str,
    slug_to_id: Optional[Dict[str, str]] = None,
    known_ids: Optional[Iterable[str]] = None,
) -> Optional[dict]:
    """The Docs `Link` union member for a markdown href.

    Returns ``{"url": ...}`` for a URL, ``{"headingId": ...}`` for a resolvable
    anchor, and None for an anchor that resolves to nothing — never a `url`
    link holding a `#fragment`, which is the dead link this module exists to
    stop writing. A None return is a caller's cue to write no link at all and
    to report the anchor — never to fall back to a `url`.
    """
    if not is_anchor(href):
        return {"url": href}
    heading_id = resolve_anchor(href, slug_to_id or {}, known_ids)
    return {"headingId": heading_id} if heading_id else None


def anchors_in(nodes: Iterable[object]) -> List[str]:
    """Every distinct internal anchor used by a node list, in first-use order."""
    seen: Dict[str, None] = {}
    for node in nodes:
        for span in getattr(node, "spans", None) or []:
            href = getattr(span, "link", None)
            if isinstance(href, str) and is_anchor(href) and href not in seen:
                seen[href] = None
    return list(seen)


def unresolved_anchors(
    target_nodes: Sequence[object],
    document_nodes: Sequence[object] = (),
) -> List[str]:
    """Anchors in ``target_nodes`` that no heading can satisfy, in use order.

    Checked against the headings of the markdown being pushed *and* of the
    document as it stands, because both can supply a target: a heading this
    push is about to create is only in the markdown, while a `#h.abc123` id
    emitted by an earlier pull is only in the document.

    This is the ``--dry-run`` view, computed before anything is written and
    therefore an approximation. The authoritative answer is
    DocsRequestBuilder.unresolved_anchor_links(), which runs in pass 2 against
    the document as actually written.

    It **under-reports and never over-reports** — the direction that matters,
    since a dry-run that invented a problem would be worse than one that misses
    it. Three causes, all of which count as resolvable here and are caught only
    by pass 2:

    * a heading this push *creates* — its slug is already in the markdown;
    * a heading this push *deletes*, whose id is still in the document;
    * a heading present in both that the document reports with no `headingId`.

    Do not restate this as "only" one cause. Each of the three was measured.
    """
    slug_to_id = dict(heading_slug_to_id(document_nodes))
    resolvable = {
        unicodedata.normalize("NFC", slug)
        for slug in list(heading_slugs(target_nodes)) + list(slug_to_id)
    }
    known_ids = {
        heading_id
        for _text, heading_id in _heading_texts_and_ids(document_nodes)
        if heading_id
    }
    return [
        href
        for href in anchors_in(target_nodes)
        if anchor_target(href) not in resolvable and anchor_target(href) not in known_ids
    ]
