"""Internal markdown anchors on the Confluence backend — reported, not resolved.

`[A1](#a1-current-state)` is written to Confluence as a literal `#a1-current-state`
href (`adf/nodes.py`'s `link`), which is the same dead link the Google Docs backend
was fixed for: it renders, a reader clicks it, and nothing happens.

**Why this reports instead of resolving.** Confluence heading anchors are not bare
slugs. They are page-scoped and generated by Confluence's own rules, and getting
the format wrong produces exactly what this module exists to prevent — a link that
looks right and goes nowhere. No Confluence instance was available to establish
the format against, so resolving it here would be a guess presented as a fix.

Making the failure loud is the part that can be done correctly today. A warning
costs the author one line and tells them to use plain text, which is the same
workaround the Google Docs report recommends; a wrong href costs every reader of
the page a dead click and tells nobody.

To finish this properly, someone with a live instance needs to establish: what
anchor Confluence generates for a heading, whether the `{anchor}` macro is
required for a reliable target, and whether the anchor is page-title-scoped.
"""
from __future__ import annotations

import re
from typing import List

# Inline markdown link whose destination is a fragment. Anchored on "](#" so a
# bare "#foo" in prose or inside a code fence is not matched.
_ANCHOR_LINK = re.compile(r"\]\(#(?P<target>[^)\s]+)\)")


def internal_anchors_in_markdown(content: str) -> List[str]:
    """Every distinct `#fragment` link destination in ``content``, in use order."""
    seen: List[str] = []
    for match in _ANCHOR_LINK.finditer(content):
        anchor = "#" + match.group("target")
        if anchor not in seen:
            seen.append(anchor)
    return seen


def render_dead_anchors(anchors: List[str]) -> str:
    """Warn that internal anchors were written as literal, non-working hrefs."""
    shown = anchors[:5]
    more = len(anchors) - len(shown)
    lines = [
        f"⚠ {len(anchors)} internal anchor(s) were written as literal `#fragment` "
        f"links, which Confluence does not resolve — a reader clicking one lands "
        f"nowhere. Use plain text instead until anchor support lands:"
    ]
    lines += [f"    • {anchor}" for anchor in shown]
    if more:
        lines.append(f"    • … and {more} more")
    return "\n".join(lines)
