"""Internal markdown anchors on the Confluence backend — reported, not resolved.

`[A1](#a1-current-state)` is written to Confluence as a literal `#a1-current-state`
href (`adf/nodes.py`'s `link`), which is the same dead link the Google Docs backend
was fixed for: it renders, a reader clicks it, and nothing happens.

**Why this reports instead of resolving.** Confluence heading anchors are not bare
slugs. They are page-scoped and generated by Confluence's own rules, and getting
the format wrong produces exactly what this module exists to prevent — a link that
looks right and goes nowhere. No Confluence instance was available to establish
the format against, so resolving it here would be a guess presented as a fix.

Making the failure loud is the part that can be done correctly today. A warning
costs the author one line and tells them to use plain text, which is the same
workaround the Google Docs report recommends; a wrong href costs every reader of
the page a dead click and tells nobody.

To finish this properly, someone with a live instance needs to establish: what
anchor Confluence generates for a heading, whether the `{anchor}` macro is
required for a reliable target, and whether the anchor is page-title-scoped.
"""
from __future__ import annotations

import re
from typing import List

# Deliberately the *same shape* as InlineParser.PATTERNS["link"] — the pattern
# that decides what actually becomes a link — narrowed to a `#` destination:
#
#     r'\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)'
#
# An earlier version omitted the optional title, so `[A1](#a1 "Some Title")`
# reached Confluence as a dead `#fragment` href and was **not** reported: a false
# negative in the one job this module has. The two patterns must not drift.
_ANCHOR_LINK = re.compile(r"(?<!!)\[[^\]]+\]\(#(?P<target>[^)\s]+)(?:\s+\"[^\"]+\")?\)")

# Inline code, which the block parser never runs the inline parser over — so a
# link inside one is documentation, not a link.
_INLINE_CODE = re.compile(r"`[^`\n]+`")


def _strip_fenced_code(content: str) -> str:
    """Replace fenced code blocks with blank lines, in linear time.

    A regex equivalent of this (matching an opening fence, then lazily
    scanning for its close) is quadratic-or-worse on input containing many
    lines that look like fence-opens but never close: each candidate open
    forces a fresh scan to the end of the input looking for a match that
    isn't there. A single left-to-right pass over lines, tracking fence
    state, does the same job in O(n).

    An opening fence that is never closed extends to end-of-document (the
    CommonMark rule) rather than matching nothing: everything after it is
    still code, not prose, so a link inside it must not be reported.
    """
    out: List[str] = []
    in_fence = False
    fence_char = ""
    fence_len = 0
    for line in content.split("\n"):
        stripped = line.lstrip(" \t")
        if not in_fence:
            marker = stripped[:1]
            if marker in ("`", "~"):
                run = len(stripped) - len(stripped.lstrip(marker))
                if run >= 3:
                    in_fence = True
                    fence_char = marker
                    fence_len = run
                    out.append("")
                    continue
            out.append(line)
        else:
            closing = stripped.rstrip(" \t")
            if closing and closing == fence_char * len(closing) and len(closing) == fence_len:
                in_fence = False
            out.append("")
    return "\n".join(out)


def internal_anchors_in_markdown(content: str) -> List[str]:
    """Every distinct `#fragment` link destination in ``content``, in use order.

    Code is removed first. The scan is not block-aware, and a page documenting
    anchor syntax inside a ```` ```markdown ```` fence had its own example
    reported — a warning, and a non-zero exit, on a page containing no link at
    all. `![alt](#f)` is excluded too: it becomes a `media` node, so "a reader
    clicking one lands nowhere" would be the wrong thing to say about it.
    """
    prose = _INLINE_CODE.sub(" ", _strip_fenced_code(content))
    seen: List[str] = []
    for match in _ANCHOR_LINK.finditer(prose):
        anchor = "#" + match.group("target")
        if anchor not in seen:
            seen.append(anchor)
    return seen


def render_dead_anchors(anchors: List[str]) -> str:
    """Warn that internal anchors were written as literal, non-working hrefs."""
    shown = anchors[:5]
    more = len(anchors) - len(shown)
    lines = [
        f"⚠ {len(anchors)} internal anchor(s) were written as literal `#fragment` "
        f"links, which Confluence does not resolve — a reader clicking one lands "
        f"nowhere. Use plain text instead until anchor support lands:"
    ]
    lines += [f"    • {anchor}" for anchor in shown]
    if more:
        lines.append(f"    • … and {more} more")
    return "\n".join(lines)
